cmake_minimum_required(VERSION 3.21)
project(launcher VERSION 2.5.3)

# base configuration
set(NEXT_CLIENT_BUILD_VERSION_MAJOR 2)
set(NEXT_CLIENT_BUILD_VERSION_MINOR 5)
set(NEXT_CLIENT_BUILD_VERSION_PATCH 3)
set(NEXT_CLIENT_BUILD_VERSION_PRERELEASE "")

set(NEXT_CLIENT_BUILD_VERSION_PRERELEASE_APPEND "")
if (NEXT_CLIENT_BUILD_VERSION_PRERELEASE)
    set(NEXT_CLIENT_BUILD_VERSION_PRERELEASE_APPEND "-${NEXT_CLIENT_BUILD_VERSION_PRERELEASE}")
endif()
set(NEXT_CLIENT_BUILD_VERSION "${NEXT_CLIENT_BUILD_VERSION_MAJOR}.${NEXT_CLIENT_BUILD_VERSION_MINOR}.${NEXT_CLIENT_BUILD_VERSION_PATCH}${NEXT_CLIENT_BUILD_VERSION_PRERELEASE_APPEND}")
set(NEXT_LAUNCHER_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

set(CMAKE_SYSTEM_VERSION 6.0)
set(CMAKE_CXX_STANDARD 23)

set(BUILD_SHARED_LIBS OFF)

if (VCPKG_TARGET_TRIPLET STREQUAL "x86-windows-static")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
else ()
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
endif ()

# options
# cpr configuration
set(CPR_ENABLE_SSL ON)
set(CPR_USE_SYSTEM_CURL ON)

# launcher subprojects
add_subdirectory(src)

if (NEXTCLIENT_BUILD_TESTS)
    add_subdirectory(tests)
endif ()
