"Resource\OptionsSubMultiplayer.res"
{
	"NameLabel"
	{
		"ControlName" "Label"
		"fieldName" "NameLabel"
		"xpos" "26"
		"ypos" "28"
		"wide" "220"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_PlayerName"
		"textAlignment" "west"
		"associate" "NameEntry"
	}
	"NameEntry"
	{
		"ControlName" "TextEntry"
		"fieldName" "NameEntry"
		"xpos" "26"
		"ypos" "51"
		"wide" "220"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "1"
		"editable" "1"
		"maxchars" "63"
		"unicode" "1"
	}
	"PasswordLabel"
	{
		"ControlName" "Label"
		"fieldName" "PasswordLabel"
		"xpos" "270"
		"ypos" "28"
		"wide" "218"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_AdminPassword"
		"textAlignment" "west"
		"associate" "PasswordEntry"
	}
	"PasswordEntry"
	{
		"ControlName" "TextEntry"
		"fieldName" "PasswordEntry"
		"xpos" "270"
		"ypos" "51"
		"wide" "218"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "2"
		"textHidden" "1"
		"editable" "1"
		"maxchars" "63"
	}
	"SprayTitle"
	{
		"ControlName" "Label"
		"fieldName" "SprayTitle"
		"xpos" "26"
		"ypos" "102"
		"wide" "220"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_SpraypaintImage"
		"textAlignment" "west"
	}
	"LogoImage"
	{
		"ControlName" "Panel"
		"fieldName" "LogoImage"
		"xpos" "26"
		"ypos" "132"
		"wide" "64"
		"tall" "64"
		"visible" "1"
		"enabled" "1"
	}
	"SpraypaintList"
	{
		"ControlName" "CLabeledCommandComboBox"
		"fieldName" "SpraypaintList"
		"xpos" "104"
		"ypos" "132"
		"wide" "142"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "3"
	}
	"SpraypaintColor"
	{
		"ControlName" "CLabeledCommandComboBox"
		"fieldName" "SpraypaintColor"
		"xpos" "104"
		"ypos" "172"
		"wide" "142"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "4"
	}
	"SprayNote"
	{
		"ControlName" "Label"
		"fieldName" "SprayNote"
		"xpos" "26"
		"ypos" "210"
		"wide" "220"
		"tall" "44"
		"visible" "1"
		"labelText" "#GameUI_SpraypaintServerNote"
		"textAlignment" "west"
		"wrap" "1"
		"dulltext" "1"
	}
	"CrosshairLabel"
	{
		"ControlName" "Label"
		"fieldName" "CrosshairLabel"
		"xpos" "270"
		"ypos" "102"
		"wide" "218"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_CrosshairDescription"
		"textAlignment" "west"
	}
	"CrosshairImage"
	{
		"ControlName" "ImagePanel"
		"fieldName" "CrosshairImage"
		"xpos" "270"
		"ypos" "132"
		"wide" "64"
		"tall" "64"
		"visible" "1"
		"enabled" "1"
		"image" "gfx/vgui/crosshair"
		"border" "DepressedBorder"
	}
	"CrosshairTypeComboBox"
	{
		"ControlName" "CLabeledCommandComboBox"
		"fieldName" "CrosshairTypeComboBox"
		"xpos" "348"
		"ypos" "200"
		"wide" "140"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "7"
	}
	"CrosshairSizeComboBox"
	{
		"ControlName" "CLabeledCommandComboBox"
		"fieldName" "CrosshairSizeComboBox"
		"xpos" "348"
		"ypos" "132"
		"wide" "140"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "5"
	}
	"CrosshairColorComboBox"
	{
		"ControlName" "CLabeledCommandComboBox"
		"fieldName" "CrosshairColorComboBox"
		"xpos" "348"
		"ypos" "166"
		"wide" "140"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "6"
	}
	"CrosshairTranslucencyCheckbox"
	{
		"ControlName" "CCvarToggleCheckButton"
		"fieldName" "CrosshairTranslucencyCheckbox"
		"xpos" "270"
		"ypos" "230"
		"wide" "218"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "8"
		"labelText" "#GameUI_Translucent"
	}
	"CrosshairDynamic"
	{
		"ControlName" "CCvarToggleCheckButton"
		"fieldName" "CrosshairDynamic"
		"xpos" "270"
		"ypos" "254"
		"wide" "218"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "9"
		"labelText" "#GameUI_CrosshairDynamic"
	}
	"Advanced"
	{
		"ControlName" "Button"
		"fieldName" "Advanced"
		"xpos" "26"
		"ypos" "274"
		"wide" "160"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "10"
		"labelText" "#GameUI_AdvancedEllipsis"
		"command" "Advanced"
	}
	"High Quality Models"
	{
		"ControlName" "CCvarToggleCheckButton"
		"fieldName" "High Quality Models"
		"visible" "0"
		"enabled" "0"
	}
}
