"Resource\OptionsSubMouse.res"
{
	"MouseLook"
	{
		"ControlName" "CheckButton"
		"fieldName" "MouseLook"
		"xpos" "20"
		"ypos" "20"
		"wide" "160"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "1"
		"labelText" "#GameUI_MouseLook"
		"textAlignment" "west"
	}
	"MouseLookLabel"
	{
		"ControlName" "Label"
		"fieldName" "MouseLookLabel"
		"xpos" "190"
		"ypos" "20"
		"wide" "280"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_MouseLookLabel"
		"textAlignment" "west"
		"dulltext" "1"
	}
	"MouseFilter"
	{
		"ControlName" "CheckButton"
		"fieldName" "MouseFilter"
		"xpos" "20"
		"ypos" "50"
		"wide" "160"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "2"
		"labelText" "#GameUI_MouseFilter"
		"textAlignment" "west"
	}
	"MouseFilterLabel"
	{
		"ControlName" "Label"
		"fieldName" "MouseFilterLabel"
		"xpos" "190"
		"ypos" "50"
		"wide" "280"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_MouseFilterLabel"
		"textAlignment" "west"
		"dulltext" "1"
	}
	"RawInput"
	{
		"ControlName" "CheckButton"
		"fieldName" "RawInput"
		"xpos" "20"
		"ypos" "80"
		"wide" "160"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "3"
		"labelText" "#GameUI_RawInput"
		"textAlignment" "west"
	}
	"RawInputLabel"
	{
		"ControlName" "Label"
		"fieldName" "RawInputLabel"
		"xpos" "190"
		"ypos" "80"
		"wide" "280"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_RawInputLabel"
		"textAlignment" "west"
		"dulltext" "1"
	}
	"SensitivityTitle"
	{
		"ControlName" "Label"
		"fieldName" "SensitivityTitle"
		"xpos" "20"
		"ypos" "120"
		"wide" "220"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_MouseSensitivity"
		"textAlignment" "west"
		"associate" "Slider"
	}
	"Slider"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "Slider"
		"xpos" "20"
		"ypos" "142"
		"wide" "350"
		"tall" "34"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "4"
	}
	"SensitivityLabel"
	{
		"ControlName" "TextEntry"
		"fieldName" "SensitivityLabel"
		"xpos" "382"
		"ypos" "142"
		"wide" "52"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "5"
		"NumericInputOnly" "1"
	}
	"Auto-Aim"
	{
		"ControlName" "CheckButton"
		"fieldName" "Auto-Aim"
		"visible" "0"
		"enabled" "0"
	}
}
