"Resource\OptionsSubVideo.res"
{
	"Brightness"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Brightness"
		"xpos"		"22"
		"ypos"		"144"
		"wide"		"205"
		"tall"		"38"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"leftText"		"#GameUI_DARK"
		"rightText"		"#GameUI_LIGHT"
	}
	"Gamma"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Gamma"
		"xpos"		"22"
		"ypos"		"68"
		"wide"		"205"
		"tall"		"38"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"leftText"		"#GameUI_Low"
		"rightText"		"#GameUI_High"
	}
	"Resolution"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Resolution"
		"xpos"		"40"
		"ypos"		"52"
		"wide"		"160"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AspectRatio"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AspectRatio"
		"xpos"		"40"
		"ypos"		"105"
		"wide"		"160"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"VSync"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"VSync"
		"xpos"		"245"
		"ypos"		"50"
		"wide"		"210"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		"#GameUI_VSync"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Default"		"0"
	}
	"Windowed"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"Windowed"
		"xpos"		"248"
		"ypos"		"45"
		"wide"		"240"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		"#GameUI_Windowed"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Default"		"0"
	}
	"HDModels"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HDModels"
		"xpos"		"248"
		"ypos"		"95"
		"wide"		"240"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"7"
		"labelText"		"#GameUI_HDModels"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Default"		"0"
	}
	"HighVideoQuality"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HighVideoQuality"
		"xpos"		"248"
		"ypos"		"120"
		"wide"		"240"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		"High Video Quality"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Default"		"0"
	}
    "DisableMultitexture"
    {
        "ControlName"		"CheckButton"
        "fieldName"		"DisableMultitexture"
        "xpos"		"245"
        "ypos"		"86"
        "wide"		"210"
        "tall"		"24"
        "AutoResize"		"0"
        "PinCorner"		"0"
        "RoundedCorners"		"15"
        "pin_corner_to_sibling"		"0"
        "pin_to_sibling_corner"		"0"
        "visible"		"1"
        "enabled"		"1"
        "tabPosition"		"9"
        "labelText"		"#GameUI_DisableMultitexture"
        "textAlignment"		"west"
        "dulltext"		"0"
        "brighttext"		"0"
        "wrap"		"0"
        "centerwrap"		"0"
        "textinsetx"		"6"
        "textinsety"		"0"
        "autowidetocontents"		"0"
        "useproportionalinsets"		"0"
        "Default"		"0"
    }
    "StretchAspect"
    {
        "ControlName"		"CheckButton"
        "fieldName"		"StretchAspect"
        "xpos"		"245"
        "ypos"		"116"
        "wide"		"210"
        "tall"		"24"
        "AutoResize"		"0"
        "PinCorner"		"0"
        "RoundedCorners"		"15"
        "pin_corner_to_sibling"		"0"
        "pin_to_sibling_corner"		"0"
        "visible"		"1"
        "enabled"		"1"
        "tabPosition"		"10"
        "labelText"		"#GameUI_StretchAspect"
        "textAlignment"		"west"
        "dulltext"		"0"
        "brighttext"		"0"
        "wrap"		"0"
        "centerwrap"		"0"
        "textinsetx"		"6"
        "textinsety"		"0"
        "autowidetocontents"		"0"
        "useproportionalinsets"		"0"
        "Default"		"0"
    }
	"brightness label"
	{
		"ControlName"		"Label"
		"fieldName"		"brightness label"
		"xpos"		"22"
		"ypos"		"122"
		"wide"		"205"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Brightness"
		"textAlignment"		"west"
		"associate"		"Brightness"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Gamma label"
	{
		"ControlName"		"Label"
		"fieldName"		"Gamma label"
		"xpos"		"22"
		"ypos"		"46"
		"wide"		"205"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gamma"
		"textAlignment"		"west"
		"associate"		"Gamma"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"40"
		"ypos"		"28"
		"wide"		"160"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Resolution"
		"textAlignment"		"west"
		"associate"		"Resolution"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"40"
		"ypos"		"80"
		"wide"		"160"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_DisplayMode"
		"textAlignment"		"west"
		"associate"		"AspectRatio"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"fieldName"		"Label5"
		"xpos"		"22"
		"ypos"		"230"
		"wide"		"435"
		"tall"		"44"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_VideoRestart"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"AdvancedVideo"
	{
		"ControlName"		"Button"
		"fieldName"		"AdvancedVideo"
		"xpos"		"245"
		"ypos"		"170"
		"wide"		"190"
		"tall"		"22"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"11"
		"labelText"		"#GameUI_VideoAdvancedBtn"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"command"		"Advanced"
		"Default"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"1310"
		"ypos"		"90"
		"wide"		"402"
		"tall"		"585"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
