"Resource\OptionsSubAudio.res"
{
	"SFX Slider"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "SFX Slider"
"xpos" "22"
"ypos" "82"
"wide" "205"
"tall" "38"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "1"
		"leftText" "#GameUI_Low"
		"rightText" "#GameUI_High"
	}
	"SFXLabel"
	{
		"ControlName" "Label"
		"fieldName" "SFXLabel"
"xpos" "22"
"ypos" "60"
"wide" "205"
"tall" "22"
		"visible" "1"
		"enabled" "1"
		"labelText" "#GameUI_SoundEffectVolume"
		"textAlignment" "west"
		"associate" "SFX Slider"
	}
	"MP3 Volume"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "MP3 Volume"
"xpos" "22"
"ypos" "162"
"wide" "205"
"tall" "38"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "2"
		"leftText" "#GameUI_Low"
		"rightText" "#GameUI_High"
	}
	"MP3Label"
	{
		"ControlName" "Label"
		"fieldName" "MP3Label"
"xpos" "22"
"ypos" "140"
"wide" "205"
"tall" "22"
		"visible" "1"
		"enabled" "1"
		"labelText" "#GameUI_MP3Volume"
		"textAlignment" "west"
		"associate" "MP3 Volume"
	}
	"Sound Quality"
	{
		"ControlName" "CLabeledCommandComboBox"
		"fieldName" "Sound Quality"
"xpos" "250"
"ypos" "82"
		"wide" "190"
"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "3"
	}
	"QualityLabel"
	{
		"ControlName" "Label"
		"fieldName" "QualityLabel"
"xpos" "250"
"ypos" "60"
		"wide" "190"
"tall" "22"
		"visible" "1"
		"enabled" "1"
		"labelText" "#GameUI_SoundQuality"
		"textAlignment" "west"
		"associate" "Sound Quality"
	}
	"Suit Slider"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "Suit Slider"
"xpos" "250"
"ypos" "162"
		"wide" "190"
"tall" "38"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "4"
		"leftText" "#GameUI_Low"
		"rightText" "#GameUI_High"
	}
	"suit label"
	{
		"ControlName" "Label"
		"fieldName" "suit label"
"xpos" "250"
"ypos" "140"
		"wide" "190"
"tall" "22"
		"visible" "1"
		"enabled" "1"
		"labelText" "#GameUI_HEVSuitVolume"
		"textAlignment" "west"
		"associate" "Suit Slider"
	}
	"EAX"
	{
		"ControlName" "CCvarToggleCheckButton"
		"fieldName" "EAX"
		"xpos" "350"
		"ypos" "230"
		"wide" "220"
		"tall" "24"
		"visible" "0"
		"enabled" "0"
	}
	"A3D"
	{
		"ControlName" "CCvarToggleCheckButton"
		"fieldName" "A3D"
		"xpos" "350"
		"ypos" "260"
		"wide" "220"
		"tall" "24"
		"visible" "0"
		"enabled" "0"
	}
}
