"Resource\VideoAvancedDialog.res"
{
	"CVideoAdvancedDialog"
	{
		"ControlName" "CVideoAdvancedDialog"
		"fieldName" "CVideoAdvancedDialog"
		"wide" "440"
		"tall" "230"
		"visible" "1"
		"enabled" "1"
		"settitlebarvisible" "1"
		"title" "#GameUI_VideoAdvanced"
	}
	"FovFixCheckbox"
	{
		"ControlName" "CCvarToggleCheckButton"
		"fieldName" "FovFixCheckbox"
		"xpos" "22"
		"ypos" "38"
		"wide" "396"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "1"
		"labelText" "#GameUI_FovFix"
	}
	"FovAngle"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "FovAngle"
		"xpos" "54"
		"ypos" "70"
		"wide" "140"
		"tall" "30"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "2"
		"leftText" "70"
		"rightText" "100"
	}
	"FovAngleText"
	{
		"ControlName" "TextEntry"
		"fieldName" "FovAngleText"
		"xpos" "202"
		"ypos" "72"
		"wide" "40"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "3"
		"NumericInputOnly" "1"
	}
	"FovAngleLabel"
	{
		"ControlName" "Label"
		"fieldName" "FovAngleLabel"
		"xpos" "254"
		"ypos" "72"
		"wide" "164"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_FovAngle"
		"textAlignment" "west"
	}
	"ViewmodelFovAutoCheckbox"
	{
		"ControlName" "CheckButton"
		"fieldName" "ViewmodelFovAutoCheckbox"
		"xpos" "22"
		"ypos" "110"
		"wide" "24"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "4"
	}
	"FovViewmodelAngle"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "FovViewmodelAngle"
		"xpos" "54"
		"ypos" "108"
		"wide" "140"
		"tall" "30"
		"visible" "1"
		"enabled" "0"
		"tabPosition" "5"
		"leftText" "70"
		"rightText" "100"
	}
	"FovViewmodelAngleText"
	{
		"ControlName" "TextEntry"
		"fieldName" "FovViewmodelAngleText"
		"xpos" "202"
		"ypos" "110"
		"wide" "40"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "6"
	}
	"ViewmodelLabel"
	{
		"ControlName" "Label"
		"fieldName" "ViewmodelLabel"
		"xpos" "254"
		"ypos" "110"
		"wide" "164"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_FovViewModelAngle"
		"textAlignment" "west"
	}
	"FovLerpTime"
	{
		"ControlName" "CCvarSlider"
		"fieldName" "FovLerpTime"
		"xpos" "54"
		"ypos" "146"
		"wide" "140"
		"tall" "30"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "7"
	}
	"FovLerpTimeText"
	{
		"ControlName" "TextEntry"
		"fieldName" "FovLerpTimeText"
		"xpos" "202"
		"ypos" "148"
		"wide" "40"
		"tall" "22"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "8"
		"NumericInputOnly" "1"
	}
	"LerpLabel"
	{
		"ControlName" "Label"
		"fieldName" "LerpLabel"
		"xpos" "254"
		"ypos" "148"
		"wide" "164"
		"tall" "22"
		"visible" "1"
		"labelText" "#GameUI_FovLerp"
		"textAlignment" "west"
	}
	"OK"
	{
		"ControlName" "Button"
		"fieldName" "OK"
		"xpos" "196"
		"ypos" "194"
		"wide" "70"
		"tall" "23"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "9"
		"labelText" "#GameUI_OK"
		"command" "Ok"
		"Default" "1"
	}
	"Cancel"
	{
		"ControlName" "Button"
		"fieldName" "Cancel"
		"xpos" "276"
		"ypos" "194"
		"wide" "70"
		"tall" "23"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "10"
		"labelText" "#GameUI_Cancel"
		"command" "Close"
	}
	"Apply"
	{
		"ControlName" "Button"
		"fieldName" "Apply"
		"xpos" "356"
		"ypos" "194"
		"wide" "70"
		"tall" "23"
		"visible" "1"
		"enabled" "0"
		"tabPosition" "11"
		"labelText" "#GameUI_Apply"
		"command" "Apply"
	}
}
