"Resource/UI/ScoreBoard.res"
{
	"ClientScoreBoard"
	{
		"ControlName"		"CClientScoreBoardDialog"
		"fieldName"		"ClientScoreBoard"
		"xpos"		"c-270"
		"ypos"		"48"
		"wide"		"540"
		"tall"		"340"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ServerName"
	{
		"ControlName"		"Label"
		"fieldName"		"ServerName"
		"xpos"		"7"
		"ypos"		"2"
		"wide"		"250"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"PlayerList"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"		"PlayerList"
		"xpos"		"4"
		"ypos"		"0"
		"wide"		"532"
		"tall"		"340"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"autoresize"	"3"
		"linespacing"	"13"
	}
}
