#pragma once
#define LAUNCHER_VERSION "0.0.1 ("  __DATE__ " " __TIME__ ")"
#define NEXT_CLIENT_BUILD_VERSION "0.0.1"
#define NEXT_CLIENT_BUILD_VERSION_MAJOR 0
#define NEXT_CLIENT_BUILD_VERSION_MINOR 0
#define NEXT_CLIENT_BUILD_VERSION_PATCH 1
#define NEXT_CLIENT_BUILD_VERSION_PRERELEASE ""
